service: serverless-stack

package:
  individually: true

plugins:
  - serverless-middleware
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ${env:REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:use-east-1:*:*"

custom:
  middleware:
    pre:
      - src/middleware.bodyParser
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: "yarn"
  prune:
    automatic: true
    number: 5 # Number of versions to keep
  documentation:
    api:
      info:
        version: 0.1.0
        title: Serverless stack
        description: From tutorial serverless-stack.com
    models:
      - name: CreateNoteRequest
        contentType: "application/json"
        schema:
          required:
            - email
            - password
          properties:
            content:
              type: string
            attachment:
              type: string
              pattern: "(.jpg|.png|.jpeg)$"

functions:
  - ${file(serverless-functions.yml)}
resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/request-body-validation.yml)}
