service: serverless-stack

package:
  individually: true

plugins:
  - serverless-middleware
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.14
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:use-east-1:*:*"

custom:
  middleware:
    pre:
      - src/middleware.bodyJson
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: "yarn"
  prune:
    automatic: true
    number: 5 # Number of versions to keep

functions:
  create:
    handler: src/functions/create.default
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
